require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/yarns", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Yarn. As you add validations to Yarn, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Yarn.create! valid_attributes
      get yarns_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      yarn = Yarn.create! valid_attributes
      get yarn_url(yarn)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_yarn_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      yarn = Yarn.create! valid_attributes
      get edit_yarn_url(yarn)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Yarn" do
        expect {
          post yarns_url, params: { yarn: valid_attributes }
        }.to change(Yarn, :count).by(1)
      end

      it "redirects to the created yarn" do
        post yarns_url, params: { yarn: valid_attributes }
        expect(response).to redirect_to(yarn_url(Yarn.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Yarn" do
        expect {
          post yarns_url, params: { yarn: invalid_attributes }
        }.to change(Yarn, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post yarns_url, params: { yarn: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested yarn" do
        yarn = Yarn.create! valid_attributes
        patch yarn_url(yarn), params: { yarn: new_attributes }
        yarn.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the yarn" do
        yarn = Yarn.create! valid_attributes
        patch yarn_url(yarn), params: { yarn: new_attributes }
        yarn.reload
        expect(response).to redirect_to(yarn_url(yarn))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        yarn = Yarn.create! valid_attributes
        patch yarn_url(yarn), params: { yarn: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested yarn" do
      yarn = Yarn.create! valid_attributes
      expect {
        delete yarn_url(yarn)
      }.to change(Yarn, :count).by(-1)
    end

    it "redirects to the yarns list" do
      yarn = Yarn.create! valid_attributes
      delete yarn_url(yarn)
      expect(response).to redirect_to(yarns_url)
    end
  end
end
